version: "3"

services:
  hass:
    image: homeassistant/home-assistant:beta
    restart: unless-stopped
    ports:
      - 8123:8123
    volumes:
      - ${PWD}/.hass_dev:/config
    networks:
      - test_net

  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${PWD}/.mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${PWD}/.mosquitto/data:/mosquitto/data
      - ${PWD}/.mosquitto/log:/mosquitto/log
    networks:
      - test_net

  sonnenbatterie2mqtt:
    image: ghcr.io/flo2410/sonnenbatterie2mqtt:latest
    restart: unless-stopped
    environment:
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
      - SONNENBATTERIE_IP=10.0.0.177
    networks:
      - test_net

networks:
  test_net:
