export enum SonnenbatterieParameter {
  POWER_GENERATION = "M03",
  POWER_CONSUMPTION = "M04",
  STATE_OF_CHARGE = "M05",
  OPERATING_MODE = "M06",
  PHASE_L1_CONSUMPTION = "M07",
  PHASE_L2_CONSUMPTION = "M08",
  PHASE_L3_CONSUMPTION = "M09",
  PHASE_L1_MAX_CONSUMPTION = "M10",
  PHASE_L2_MAX_CONSUMPTION = "M11",
  PHASE_L3_MAX_CONSUMPTION = "M12",
  DISCHARGE_POWER = "M34",
  CHARGING_POWER = "M35",
}

export enum SonnenbatterieOperattingMode {
  STANDBY = 10,
  TRICKLE_CHARGE = 11,
  CHARGING = 13,
  DISCHARGING = 15,
}
